build:
  image: drone/golang:1.5
  commands:
    - export msys_arch=$$arch
    - echo 'Build teaci/msys$$arch:testing image using drone docker plugin...'
    - ./generate.sh

notify:
  irc:
    prefix: build
    nick: msys2-docker
    channel: wine-ci
    server:
      host: chat.freenode.net
      port: 6667

publish:
  docker:
    file: Dockerfile.$$arch
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: teaci/msys$$arch
    tag:
      - "testing"
      - "w1.9.10-m2.5.1-4t"
    when:
      repo: TeaCI/msys2-docker # case sensitive
      branch: master

matrix:
  arch:
    - 64
    - 32
