FROM teaci/wine-staging
MAINTAINER Qian Hong <qhong@codeweavers.com>
# Work around https://bugs.wine-staging.com/show_bug.cgi?id=682
RUN wget http://security.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6_2.5.2-1ubuntu2_i386.deb && wget http://security.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6_2.5.2-1ubuntu2_amd64.deb && dpkg -i libfreetype6_2.5.2-1ubuntu2_amd64.deb libfreetype6_2.5.2-1ubuntu2_i386.deb
# Work around https://bugs.wine-staging.com/show_bug.cgi?id=626
ENV WINPTY_SHOW_CONSOLE 1
COPY msys32-env /etc/
COPY msys64-env /etc/
COPY msys2-shell /usr/bin/
COPY msys2-rebase /usr/bin/
COPY msys32-init /usr/bin/
COPY msys64-init /usr/bin/
COPY msys32 /usr/bin/
COPY msys64 /usr/bin/
COPY mingw32 /usr/bin/
COPY mingw64 /usr/bin/
RUN msys64-init
RUN msys64 -c "pacman -Syy --noconfirm --noprogressbar pacman"
RUN msys64 -c "pacman -Suu --needed --noconfirm --noprogressbar"
RUN msys64 -c "pacman -Suu --needed --noconfirm --noprogressbar && pacman -Scc --noconfirm"
RUN msys64 -c "pacman -S --needed --noconfirm --noprogressbar base-devel &&  pacman -Scc --noconfirm"
RUN msys64 -c "pacman -S --needed --noconfirm --noprogressbar msys2-devel && pacman -Scc --noconfirm"
RUN msys64 -c "pacman -S --needed --noconfirm --noprogressbar mingw-w64-x86_64-toolchain && pacman -Scc --noconfirm"
RUN msys64 -c "pacman -S --needed --noconfirm --noprogressbar git subversion && pacman -Scc --noconfirm"
RUN msys64 -c "pacman -S --needed --noconfirm --noprogressbar mingw-w64-cross-crt-git" # FIXME: investigate mingw-w64-cross-crt-clang-git issue
RUN msys64 -c "cp -f /usr/bin/false /usr/bin/tput"
#RUN msys2-rebase rebase is not required for 64 bit
