#!/bin/bash

exit 0

#FIXME rebase is not required on 64 bit, this script could be replaced to a stub script
. /etc/msys64-env

pushd ${MSYS_ROOT} > /dev/null
WINEDEBUG=-all DISPLAY=:55.0 wine wineconsole --backend=curses autorebase.bat > /dev/null ; wineserver -w
popd > /dev/null
