#!/bin/bash

set -e

if [ "${DEBUG_WRAPPER}" = "true" ]
then
    set -x
fi

# workaround https://bugs.wine-staging.com/show_bug.cgi?id=403
if [ "${DRONE}" = "true" ]
then
    if ! [ -d /drone/wineprefix ]
    then
        mv "${WINEPREFIX}" /drone/wineprefix
    fi
    export WINEPREFIX=/drone/wineprefix
    export MSYS_ROOT=${WINEPREFIX}/drive_c/msys32
fi

if [ "${DISPLAY}" = "" ]
then
    export DISPLAY=:95
    Xvfb :95 -ac -reset -terminate -screen 0 800x600x16 2>/dev/null &
    sleep 3
fi

if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
    echo  Usage:  $0 "-c commandline"
    echo "      " $0 "script-file"
    echo "      " cat script-file \| $0 
    echo
    exit
fi

if [ "${WINEDEBUG}" = "" ]
then
    export WINEDEBUG=fixme-all
fi

EXIT_CODE=exit_code.$$

if [ "${DRONE_BUILD_DIR}" ]
then
    if ! [ -d ${MSYS_ROOT}/${DRONE_BUILD_DIR} ]
    then
        DRONE_BUILD_DIR_PARENT=$(dirname ${DRONE_BUILD_DIR})
        mkdir -p ${MSYS_ROOT}/${DRONE_BUILD_DIR_PARENT}
        ln -s ${DRONE_BUILD_DIR} ${MSYS_ROOT}/${DRONE_BUILD_DIR}
    fi
    MSYS_INIT_DIR=${MSYS_ROOT}/${DRONE_BUILD_DIR}
fi

if [ "${MSYS_INIT_DIR}" ]
then
    cd ${MSYS_INIT_DIR}
else
    cd ${MSYS_ROOT} # FIXME
fi

UNIXPWD=`pwd`
WINPWD=`winepath -w ${UNIXPWD}`
WINPWD=${WINPWD//\\/\/} # replace \ to /


if [ "${DEBUG_WRAPPER}" = "true" ]
then
    echo "MSYS2 shell in ${MSYS_ROOT} in Wine on Linux"
    echo "Entering MSYS2 shell >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
fi

if [ "$#" = "0" ]
then
    cat > ${MSYS_ROOT}/tmp/command.sh
    wine ${MSYS_ROOT}/usr/bin/mintty.exe --log - -e /usr/bin/bash.exe -l -c "(cd \"${WINPWD}\"; bash -e < /tmp/command.sh || echo \$? > ${EXIT_CODE})" | tr -d '\r'
elif [ "$1" = "-c" ]
then
    COMMAND=${@:2}
    # Emulate MSYS2 COMMAND line prompt
    echo ${USER}@${HOSTNAME} ${MSYSTEM} ${WINPWD}
    echo \$ ${COMMAND}
    wine ${MSYS_ROOT}/usr/bin/mintty.exe --log - -e /usr/bin/bash.exe -l -c "(cd \"${WINPWD}\"; bash -e -c \"${COMMAND}\" || echo \$? > ${EXIT_CODE})" | tr -d '\r'
else
set -x
    pushd `dirname $1` > /dev/null
    UNIXPATH=`pwd`
    popd > /dev/null
    WINPATH=`winepath -w ${UNIXPATH}`
    COMMAND_FILE=${WINPATH}\\`basename $1`
    # Emulate MSYS2 COMMAND line prompt
    echo ${USER}@${HOSTNAME} ${MSYSTEM} ${WINPWD}
    echo \$ ${COMMAND_FILE}
    wine ${MSYS_ROOT}/usr/bin/mintty.exe --log - -e /usr/bin/bash.exe -l -c "(cd \"${WINPWD}\"; bash -e \"${COMMAND_FILE}\" || echo \$? > ${EXIT_CODE})" | tr -d '\r'
fi

if [ "$DEBUG_WRAPPER" = "true" ]
then
    echo "Leaving MSYS2 shell <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
fi

wineserver -w

if test -f ${EXIT_CODE}
then
    # clean up
    exit_code=$(cat ${EXIT_CODE})
    rm -f ${EXIT_CODE}

    if [ "${DEBUG_WRAPPER}" = "true" ]
    then
        echo msys2-shell executed \`$COMMAND\` failed with exit code ${exit_code}.
        echo
    fi
    exit ${exit_code}
fi

if [ "${DEBUG_WRAPPER}" = "true" ]
then
    echo msys2-shell executed \`$COMMAND\` successfully.
fi
echo
