#!/bin/bash

set -e

. /etc/msys32-env

# hack - wineboot without display, create wineprefix in a quick way, workaround wineboot event timeout waiting for gecko and mono
WINEDEBUG=-all DISPLAY=:55.0 wineboot; wineserver -w
WINEDEBUG=-all DISPLAY=:55.0 winetricks nocrashdialog; wineserver -w

if test -d ${MSYS_ROOT}
then
    echo Already initialized.
else
    pushd ${WINEPREFIX}/drive_c
    wget https://mirrors.tea-ci.org/msys2/distrib/i686/msys2-base-i686-20160205.tar.xz
    tar xf msys2-base-i686-*.tar.xz
    rm msys2-base-i686-*.tar.xz
    msys32 -c echo Init MSYS2 done.

    echo "Server = https://mirrors.tea-ci.org/msys2/mingw/i686" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw32
    echo "Server = https://mirrors.tea-ci.org/msys2/mingw/i686" >> ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw32

    echo "Server = https://mirrors.tea-ci.org/msys2/mingw/x86_64" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw64
    echo "Server = https://mirrors.tea-ci.org/msys2/mingw/x86_64" >> ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw64

    echo "Server = https://mirrors.tea-ci.org/msys2/msys/i686" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.msys
    echo "Server = https://mirrors.tea-ci.org/msys2/msys/i686" >> ${MSYS_ROOT}/etc/pacman.d/mirrorlist.msys

    popd
fi
