#!/bin/bash

set -e
set -x
export DISPLAY=:95
Xvfb :95 -ac -screen 0 800x600x16 &
XVFB_PID=$!
#exec 2<&-

if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
    echo  Usage:  $0 "-c commandline"
    echo "      " $0 "script-file"
    echo "      " $0
    exit
fi

. /etc/msys2-env

export MSYSTEM=MSYS
export WINEDEBUG=fixme-all
#export WINEDEBUG=tid,console

SCRIPT_FILE=typescript.$$
EXIT_CODE=exit_code.$$

# emulate travis_wait
#(for i in {1..60}; do sleep 60; echo timestamp:$i; done) &
#ALIVE_PING=$!

cd /root/.wine/drive_c/msys32
pwd
UNIXPWD=`pwd`
WINPWD=`winepath -w ${UNIXPWD}`
WINPWD=${WINPWD//\\/\/} # replace \ to /

echo
echo "Entering MSYS2 shell >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"

if [ "$#" = "0" ]
then
    (wineconsole $MSYS_ROOT/usr/bin/script.exe ${SCRIPT_FILE} -q -f -e -c "/usr/bin/bash.exe -l -c \"cd \\\"${WINPWD}\\\"; bash\"") &
elif [ "$1" = "-c" ]
then
    COMMAND=${@:2}
    (wineconsole $MSYS_ROOT/usr/bin/script.exe ${SCRIPT_FILE} -q -f -e -c "/usr/bin/bash.exe -l -c \"(cd \\\"${WINPWD}\\\"; bash -e -c \\\"${COMMAND}\\\"|| echo \\\$? > ${EXIT_CODE})\"") &
    # Emulate MSYS2 COMMAND line prompt
    echo ${USER}@${HOSTNAME} ${MSYSTEM} ${WINPWD}
    echo \$ ${COMMAND}
else
    pushd `dirname $1` > /dev/null
    UNIXPATH=`pwd`
    popd > /dev/null
    WINPATH=`winepath -w ${UNIXPATH}`
    COMMAND=${WINPATH}\\`basename $1`
    (wineconsole $MSYS_ROOT/usr/bin/script.exe ${SCRIPT_FILE} -q -f -e -c "/usr/bin/bash.exe -l -c \"(cd \\\"${WINPWD}\\\"; bash -e \\\"${COMMAND}\\\" || echo \\\$? > ${EXIT_CODE})\"") &
    # Emulate MSYS2 COMMAND line prompt
    echo ${USER}@${HOSTNAME} ${MSYSTEM} ${WINPWD}
    echo \$ ${COMMAND}
fi

tail -F ${SCRIPT_FILE} --pid=$! 2> /dev/null || return 0
ls -lh ${SCRIPT_FILE}
cat ${SCRIPT_FILE}
echo "Leaving MSYS2 shell <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

rm -f ${SCRIPT_FILE}

#if test -d /proc/${ALIVE_PING}
#then
#    kill -9 ${ALIVE_PING}
#fi

wineserver -k
kill -9 $XVFB_PID
rm -vf /tmp/.X95-lock
if test -f ${EXIT_CODE}
then
    # clean up
    exit_code=$(cat ${EXIT_CODE})
    rm -f ${EXIT_CODE}
    echo msys2-shell executed \`$COMMAND\` failed with exit code ${exit_code}.
    echo
    exit ${exit_code}
fi

echo msys2-shell executed \`$COMMAND\` successfully.
